
version: 2.1

orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: build-doc-static
          command: mkdocs build
      - run:
          name: build-docker-image
          command: docker build . -t="docs-image"
      - run:
          name: push-docker-image
          command: |
            docker tag docs-image ${DOCKER_REGISTRY_PATH}
            docker push ${DOCKER_REGISTRY_PATH}
workflows:
  sample: 
    jobs:
      - build-and-test
