
version: 2.1

orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: build-doc-static
          command: mkdocs build
      - run:
          name: push-docker-image
          command: |
             docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
             docker build . --tag=$DOCKER_USERNAME/rcs-docs:$CIRCLE_BRANCH; 
             docker push $DOCKER_USERNAME/rcs-docs:$CIRCLE_BRANCH;
workflows:
  sample: 
    jobs:
      - build-and-test
